services:
  - type: web
    name: travel-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: travel-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
